versions: 2.1

commands:
  sayHello:
    description: ""
    parameters:
      name:
        type: string
        default: "World"
    steps:
      - run: echo "Hello << parameters.name >>"

jobs:
  myJob:
    docker:
      - image: cimg/base:stable
    steps:
      - sayHello:
        name: Alice

workflows:
  myWorkflow:
    - myJob
