# reference:
# https://circleci.com/docs/2.0/reusing-config/#parameter-types
version: 2.1

commands: 
  print_param_values: # a reusable command with parameters
    description: "demonstrate how does different type of parameter injection work"
    parameters:
      a_string:
        type: string
        default: "Hello World"
      a_integer:
        type: integer
        default: 200
      # a_boolean:
      #   type: boolean
      #   default: yes
      # a_enum:
      #   type: enum
      #   enum: ["a", "b", "c"]
    steps:
      - run: echo "<< parameters.a_string >>"
      - run: echo "<< parameters.a_integer >>"
      # - run: echo << parameters.a_boolean >>
      # - run: echo << parameters.a_enum >>

jobs:
  my_job:
    docker:
      - image: cimg/base:stable
    steps:
      # if you don't want to pass any parameters (use default), you should do ``- print_param_values``
      # if you need to pass parameters value, you should do ``- print_param_values``
      - print_param_values: # call command "print_param_values", pass parameters as key value pair
        a_string: "Hello Alice"
        # a_integer: 200
        # a_boolean: yes
        # a_enum: c

workflows:
  my_workflow:
    jobs:
      - my_job
