version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run: aws s3 ls
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws-eq-sanhe-admin

