version: 2.1

executors:
  python-docker:
    docker:
      - image: python:3.6.12-alpine

jobs:
  test:
    executor: python-docker
    steps:
      - &run_pwd run_pwd: pwd
      - *run_pwd

workflows:
  my-workflow:
    jobs:
      - test
