# reference:
# - https://circleci.com/docs/2.0/reusing-config/#using-the-parameters-declaration
version: 2.1

commands: 
  say_hello: # a reusable command with parameters
    description: "demonstarte a simple resuable command with parameters"
    parameters:
      yourname: # watchout, some key is reserved keyword, and cannot be used as parameter name
        type: string
        default: "World"
    steps:
      - run: echo "Hello << parameters.yourname >>" # << paramters.$parameterName >> is variable replacement injection

jobs:
  my_job:
    docker:
      - image: cimg/base:stable
    steps:
      - say_hello: # call command "sayHello", pass parameters as key value pair
        yourname: "Alice"

workflows:
  my_workflow:
    jobs:
      - my_job
