version: 2.1

commands: 
  sayHello: # a reusable command with parameters
    description: ""
    parameters:
      name:
        type: string
        default: "World"
    steps:
      - run: echo "Hello << parameters.name >>" # << paramters.$parameterName >> is variable replacement injection

jobs:
  myJob:
    docker:
      - image: cimg/base:stable
    steps:
      - sayHello: # call command "sayHello", pass parameters as key value pair
        name: Alice

workflows:
  myWorkflow:
    - myJob
