# this is not going to work! becaus YAML doesn't allow merging array

version: 2.1

anchors:
  - run: &say_hello
      name: say hello
      command: |
        echo Hello ${YOUR_NAME}
      environment:
        YOUR_NAME: Alice

executors:
  python-docker:
    docker:
      - image: python:3.6.12-alpine

jobs:
  test:
    executor: python-docker
    steps:
      - run: *say_hello
      - run:
          <<: *say_hello
          environment:
            YOUR_NAME: Bob

workflows:
  my-workflow:
    jobs:
      - test
