version: 2.1

commands: 
  say_hello: # a reusable command with parameters
    description: ""
    parameters:
      yourname:
        type: string
        default: "World"
    steps:
      - run: echo "Hello << parameters.yourname >>" # << paramters.$parameterName >> is variable replacement injection

jobs:
  my_job:
    docker:
      - image: cimg/base:stable
    steps:
      - say_hello: # call command "sayHello", pass parameters as key value pair
        yourname: Alice

workflows:
  my_workflow:
    jobs:
      - my_job
