version: 2.1

executors:
  python-docker:
    docker:
      - image: cimg/python:3.6.12

jobs:
  setup-python-virtualenv:
    executor: python-docker
    steps:
      - checkout
      - run:
          name: setup python virtualenv
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install python-dateutil
      - save_cache:
          key: venv-cache
          paths:
            - venv
  test:
    executor: python-docker
    steps:
      - restore_cache:
          keys:
            - venv-cache
      - run:
          name: verify if venv exists and dependencies are installed
          command: |
            ls venv/bin
            venv/bin/pip list

workflows:
  my-workflow:
    jobs:
      - setup-python-virtualenv
      - test:
          requires:
            - setup-python-virtualenv
